name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      # 1. Chạy lệnh đè thẳng vào đường dẫn chính xác của file pom.xml
      - name: Build and Run Specific Test with Maven
        run: mvn -f wk9/9.3/pom.xml clean package -Dtest=AppTest

      # 2. Upload thư mục target của bài 9.3 làm Artifact
      - name: Upload Build Artifact (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: execution-jar
          path: wk9/9.3/target/